# Generated by Django 5.1.6 on 2025-02-18 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_city_user_location'),
        ('weather', '0002_alter_weather_location_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='weather.weather'),
        ),
    ]
