# Generated by Django 5.1.6 on 2025-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('observation_time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=0, max_digits=2)),
                ('feelslike', models.DecimalField(decimal_places=0, max_digits=2)),
                ('weather_descriptions', models.CharField(max_length=255)),
                ('wind_speed', models.DecimalField(decimal_places=0, max_digits=2)),
                ('humidity', models.DecimalField(decimal_places=0, max_digits=2)),
                ('visibility', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
