# Generated by Django 5.1.6 on 2025-02-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_location_alter_weather_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='observation_time',
        ),
    ]
